global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alfred_meshcheryakov'
