version: '3'
services:

  fluentd:
    image: ${USER_NAME}/fluentd:${SERVICES_VERSION}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:6.5.4
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net
      - front_net

  kibana:
    image: kibana:6.5.4
    ports:
      - "5601:5601"
    networks:
      - back_net
      - front_net

networks:
  back_net:
  front_net:
