version: '3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
      - front_net

  ui:
    image: ${USER_NAME}/ui:${SERVICES_VERSION}
    ports:
      - ${PORT_DST}:${PORT_DST}/tcp
    networks:
      - back_net
      - front_net

  post:
    image: ${USER_NAME}/post:${SERVICES_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net
   

  comment:
    image: ${USER_NAME}/comment:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net



volumes:
  post_db:

networks:
  back_net:
  front_net:
