version: '3.5'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${SERVICES_VERSION}
    ports:
      - ${PORT_DST}:${PORT_DST}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  prometheus_data:

volumes:
  post_db:

networks:
  front_net:
    name: front_net
  back_net:
    name: front_net
