version: '3.5'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USER_NAME}/ui:${SERVICES_VERSION}
    ports:
      - ${PORT_DST}:${PORT_DST}/tcp
    networks:
      - front_net

  post:
    image: ${USER_NAME}/post:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
    name: front_net
  back_net:
    name: front_net
