version: '3.5'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${SERVICES_VERSION}
    ports:
      - ${PORT_DST}:${PORT_DST}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${SERVICES_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
    name: front_net
  back_net:
    name: front_net
